substitutions:
  api_key: !secret bath-2-switch-1_api_key
  board: esp01_1m
  devicename: bath-2-switch-1
  icon: mdi:lightbulb
  room: Bath 2
  device: Switch 1
  automation_name: bath_2_light_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_athom.yaml
