substitutions:
  api_key: !secret bath-1-light-1_api_key
  devicename: bath-1-light-1
  icon: mdi:lightbulb
  room: Bath 1
  device: Light 1
  restore: RESTORE_DEFAULT_ON
  light_group: bath_1_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
