substitutions:
  api_key: !secret bath-2-light-2_api_key
  devicename: bath-2-light-2
  icon: mdi:lightbulb
  room: Bath 2
  device: Light 2
  restore: RESTORE_DEFAULT_ON
  light_group: bath_2_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
