substitutions:
  api_key: !secret bath-2-switch-1_api_key
  devicename: bath-2-switch-1
  icon: mdi:lightbulb
  room: Bath 2
  device: Switch 1
  automation_name: bath_2_lights_automation
  update_time: 10s
  light_group: bath_2_lights
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include configs/switch_ha.yaml
