substitutions:
  api_key: !secret bath-1-switch-1_api_key
  devicename: bath-1-switch-1
  icon: mdi:lightbulb
  room: Bath 1
  device: Switch 1
  automation_name: bath_1_lights
  update_time: 10s
  light_group: bath_1_lights
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include configs/switch_ha.yaml
