substitutions:
  api_key: !secret bath-1-switch-1_api_key
  board: esp01_1m
  devicename: bath-1-switch-1
  icon: mdi:light-switch
  room: Bath 1
  device: Switch 1
  automation_name: bath_1_light_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_gosund.yaml
