substitutions:
  api_key: !secret bath-2-switch-1_api_key
  automation_name: bath_2_light_automation
  board: esp01_1m
  device: Switch 1
  devicename: bath-2-switch-1
  icon: mdi:light-switch
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Bath 2

<<: !include configs/switch_athom.yaml
