substitutions:
  api_key: !secret bath-1-heater_api_key
  board: esp01_1m
  devicename: bath-1-heater
  icon: mdi:radiator
  room: Bath 1
  device: Heater
  automation_name: bath_1_heater_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
