substitutions:
  api_key: !secret bath-1-switch-2_api_key
  automation_name: bath_1_fan_automation
  board: esp01_1m
  device: Switch 2
  devicename: bath-1-switch-2
  icon: mdi:light-switch
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Bath 1

<<: !include configs/switch_gosund.yaml
