substitutions:
  api_key: !secret bath-2-switch-2_api_key
  devicename: bath-2-switch-2
  icon: mdi:fan
  room: Bath 2
  device: Switch 2
  automation_name: bath_2_fan
  update_time: 10s
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_relay_ha.yaml
