substitutions:
  api_key: !secret bath-1-light-3_api_key
  devicename: bath-1-light-3
  icon: mdi:lightbulb
  room: Bath 1
  device: Light 3
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: bath_1_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
