substitutions:
  api_key: !secret bedroom-1-lamp_api_key
  devicename: bedroom-1-lamp
  icon: mdi:lamp
  room: Bedroom 1
  device: Lamp
  automation_name: bedroom_1_lamp
  update_time: 10s
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
