substitutions:
  devicename: bedroom-1-bed
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_pass
  domain: !secret domain
  use_address: 10.0.41.9
  password: !secret esphome_password
  ntp_server: 10.0.2.1
  room: Bedroom 1
  device: Bed

esphome:
  name: ${devicename}
  platform: ESP32
  board: wemos_d1_mini32

time:
  - platform: sntp
    id: sntp_time
    servers: ${ntp_server}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  domain: ${domain}
  use_address: ${use_address}

  ap:
    ssid: ${devicename}
    password: ${password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

logger:
#  level: VERY_VERBOSE
  level: DEBUG

api:
  password: ${password}

ota:
  password: ${password}

web_server:
  port: 80

switch:
  - platform: restart
    name: ${room} ${device} Restart

status_led:
    pin:
      number: 2
      inverted: true

sensor:
  - platform: adc
    pin: GPIO34
    name: ${room} ${device}
    update_interval: .5s
    id: bed_adc
    attenuation: 11db
    filters:
#      - multiply: 3.8
      - sliding_window_moving_average:
          window_size: 10
          send_every: 2 # 10 second updates @ 1 second scan interval.
          send_first_at: 2

#  - platform: homeassistant
#    internal: true
#    id: "threshold"
#    entity_id: input_number.bedroom_1_bed_threshold
#
#binary_sensor:
#  - platform: template
#    name: "Bedroom 1 Bed Occupancy"
#    lambda: return (id(bed_adc).state < id(threshold).state);
