substitutions:
  api_key: !secret bedroom-1-bed_api_key
  devicename: bedroom-1-bed
  room: Bedroom 1
  device: Bed
  update_interval: .1s
  log_level: DEBUG

esphome:
  name: ${devicename}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: recommended

packages:
  api: !include /config/common/api.yaml
#  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

status_led:
    pin:
      number: 2
      inverted: true

sensor:
  - platform: adc
    pin: GPIO34
    name: ADC
    update_interval: ${update_interval}
    accuracy_decimals: 5
    id: bed_adc
    attenuation: auto
    filters:
      - exponential_moving_average:
          send_every: 1
#          alpha: 0.08
          alpha: 0.1
#      - sliding_window_moving_average:
#          window_size: 10
#          send_every: 1
#      - lambda: |-
#          float MIN = 2.4;
#          float MAX = 3.1;
#          if ( MIN <= x && x <= MAX) return x;
#          else return {};
