substitutions:
  api_key: !secret bedroom-1-light-1_api_key
  devicename: bedroom-1-light-1
  icon: mdi:lightbulb
  room: Bedroom 1
  device: Light 1
  restore: RESTORE_DEFAULT_ON
  light_group: bedroom_1_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
