substitutions:
  api_key: !secret bedroom-2-light-2_api_key
  devicename: bedroom-2-light-2
  icon: mdi:lightbulb
  room: Bedroom 2
  device: Light 2
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: bedroom_2_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
