substitutions:
  api_key: !secret bedroom-1-switch-1_api_key
  automation_name: bedroom_1_light_automation
  board: esp32-c3-devkitm-1
  device: Switch 1
  devicename: bedroom-1-switch-1
  espnow_peer_mac: 54:43:B2:3F:44:50
  framework: esp-idf
  icon: mdi:light-switch
  log_level: DEBUG
  restore: ALWAYS_ON
  room: Bedroom 1

<<: !include configs/switch_athom_esp32_espnow.yaml
