substitutions:
  api_key: !secret bedroom-1-light-3_api_key
  devicename: bedroom-1-light-3
  icon: mdi:lightbulb
  room: Bedroom 1
  device: Light 3
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: bedroom_1_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
