substitutions:
  api_key: !secret bedroom-1-shelly_api_key
  devicename: bedroom-1-shelly
  max_power: "3600.0"
  max_temp: "90.0"
  thres_temp: "75.0"
  icon1: mdi:lightbulb
  icon2: mdi:fan
  room: Bedroom 1
  device: Shelly
  channel_1: Light
  channel_2: Fan
  update_time: 10s
  light_group: bedroom_1_lights
  log_level: DEBUG

<<: !include /config/configs/shelly_2pm_ha.yaml
