substitutions:
  api_key: !secret bedroom-1-closet-light_api_key
  devicename: bedroom-1-closet-light
  icon: mdi:lightbulb
  room: Bedroom 1 Closet
  device: Light
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10.yaml
