substitutions:
  api_key: !secret bedroom-1-ac_api_key
  board: esp01_1m
  devicename: bedroom-1-ac
  icon: mdi:snowflake
  room: Bedroom 1
  device: AC
  automation_name: bedroom_1_ac_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
