substitutions:
  api_key: !secret bedroom-1-bed_api_key
  board: wemos_d1_mini32
  devicename: bedroom-1-bed
  room: Bedroom 1
  device: Bed
  update_interval: .1s
  log_level: DEBUG

packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  esp32: !include /config/common/esp32.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

status_led:
    pin:
      number: 2
      inverted: true
      ignore_strapping_warning: true

globals:
  - id: bed_occupied_state
    type: bool
    restore_value: yes
    initial_value: 'false'
binary_sensor:
  - platform: template
    name: Occupancy
    id: bed_occupancy
    icon: mdi:bed
    device_class: occupancy
    lambda: |-
      if (id(change).has_state() && id(std_dev).has_state()) {
        float change_val = id(change).state;
        float stddev_val = id(std_dev).state;
        if (stddev_val >= 0.08) {
          if (change_val <= -0.24) {
            id(bed_occupied_state) = true;
            return true;
          } else if (change_val >= 0.24) {
            id(bed_occupied_state) = false;
            return false;
          }
        }
      }
      return id(bed_occupied_state);
sensor:
  - platform: adc
    pin:
      number: 34
    name: ADC
    update_interval: ${update_interval}
    accuracy_decimals: 5
    id: bed_adc
    internal: true
    attenuation: auto
    filters:
      - exponential_moving_average:
          send_every: 1
          alpha: 0.1
          send_first_at: 1
  - platform: copy
    source_id: bed_adc
    name: Standard Deviation
    id: std_dev
    internal: true
    unit_of_measurement: V
    accuracy_decimals: 5
    device_class: voltage
    state_class: measurement
    filters:
      - lambda: |-
          const uint16_t window_size_ = 200;
          const uint8_t send_every_ = 2;

          static std::deque<float> queue_;
          static uint8_t send_at_ = 0;

          while (queue_.size() >= window_size_) {
            queue_.pop_front();
          }

          queue_.push_back(x);

          if (++send_at_ >= send_every_) {
            send_at_ = 0;

            float Ex = 0.0;
            float Ex2 = 0.0;
            size_t count = 0;

            if (queue_.empty()) return NAN;

            float K = queue_.front();

            for (auto v: queue_) {
              if (!std::isnan(v)) {
                count += 1;
                Ex += v - K;
                Ex2 += pow(v - K, 2);
              }
            }

            float standard_deviation = NAN;
            if (count > 1) {
              float variance = (Ex2 - pow(Ex, 2) / count) / (count - 1);
              standard_deviation = sqrt(variance);
            }

            return standard_deviation;
          }
          return {};
  - platform: copy
    source_id: bed_adc
    name: Change
    id: change
    internal: true
    unit_of_measurement: V
    accuracy_decimals: 5
    device_class: voltage
    state_class: measurement
    filters:
      - lambda: |-
          const uint16_t window_size_ = 200;
          const uint8_t send_every_ = 2;

          static std::deque<float> queue_;
          static uint8_t send_at_ = 0;

          while (queue_.size() >= window_size_) {
            queue_.pop_front();
          }

          queue_.push_back(x);

          if (++send_at_ >= send_every_) {
            send_at_ = 0;

            if (queue_.size() < 2) return NAN;

            float first = queue_.front();
            float last = queue_.back();

            return last - first;
          }
          return {};
