substitutions:
  api_key: !secret bedroom-1-ac_api_key
  automation_name: bedroom_1_ac_automation
  board: esp01_1m
  device: AC
  devicename: bedroom-1-ac
  icon: mdi:snowflake
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Bedroom 1

<<: !include /config/configs/sonoff_s31.yaml
