substitutions:
  api_key: !secret bedroom-1-lamp_api_key
  board: esp01_1m
  devicename: bedroom-1-lamp
  icon: mdi:lamp
  room: Bedroom 1
  device: Lamp
  automation_name: bedroom_1_lamp_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
