substitutions:
  api_key: !secret bedroom-2-shelly_api_key
  devicename: bedroom-2-shelly
  max_power: "3600.0"
  max_temp: "90.0"
  thres_temp: "75.0"
  icon1: mdi:lightbulb
  icon2: mdi:fan
  room: Bedroom 2
  device: Shelly
  channel_1: Light
  channel_2: Fan
  update_interval: 1s
  light_group: bedroom_2_lights
  log_level: DEBUG

<<: !include /config/configs/shelly_2pm_ha.yaml
