substitutions:
  api_key: !secret desk-light_api_key
  board: esp32-c3-devkitm-1
  color_interlock: false
  device: Light
  devicename: desk-light
  espnow_peer_mac: 94:B5:55:26:BD:2C
  framework: esp-idf
  icon: mdi:lightbulb
  log_level: DEBUG
  restore: ALWAYS_OFF
  room: Desk

<<: !include /config/configs/bulb_athom_espnow.yaml
