substitutions:
  api_key: !secret desk-light-1_api_key
  devicename: desk-light-1
  icon: mdi:lightbulb
  room: Desk
  device: Light 1
  restore: RESTORE_DEFAULT_ON
  light_group: desk_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
