substitutions:
  api_key: !secret desk-switch-panel_api_key
  board: wemos_d1_mini32
  devicename: desk-switch-panel
  ntp_server: 10.69.2.1
  room: Desk
  device: Switch Panel
  log_level: DEBUG

packages:
  api: !include /config/common/api.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  esphome: !include /config/common/esphome.yaml
  esp32: !include /config/common/esp32.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

status_led:
    pin:
      number: 2
      inverted: false

binary_sensor:
## Switch Panel
# Switch 1
  - platform: gpio
#    name: Switch Panel 1
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    id: switch1
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW1 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.bath_1_switch_1_relay
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW1 Double-Click Detected

# Switch 2
  - platform: gpio
#    name: Switch Panel 2
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    id: switch2
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW2 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.bedroom_1_shelly_light
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW2 Double-Click Detected
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.bedroom_1_lamp_switch

# Switch 3
  - platform: gpio
#    name: Switch Panel 3
    pin:
      number: GPIO05
      mode: INPUT_PULLUP
      inverted: true
    id: switch3
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW3 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.bath_2_switch_1_relay
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW3 Double-Click Detected

# Switch 4
  - platform: gpio
#    name: Switch Panel 4
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
    id: switch4
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW4 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.bedroom_2_shelly_light
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW4 Double-Click Detected

# Switch 5
  - platform: gpio
#    name: Switch Panel 5
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    id: switch5
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW5 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.hobby_room_shelly_light
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW5 Double-Click Detected

# Switch 6
  - platform: gpio
#    name: Switch Panel 6
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    id: switch6
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW6 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.kitchen_lights
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW6 Double-Click Detected
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.kitchen_lamp_switch

# Switch 7
  - platform: gpio
#    name: Switch Panel 7
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    id: switch7
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW7 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.living_room_shelly_light
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW7 Double-Click Detected

# Switch 8
  - platform: gpio
#    name: Switch Panel 8
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    id: switch8
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW8 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: switch.toggle
                    data:
                      entity_id: switch.utility_room_switch_1_relay
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW8 Double-Click Detected

# Switch 9
  - platform: gpio
#    name: Switch Panel 9
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    id: switch9
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW9 Single-Click Detected
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.front_porch_lights
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW9 Double-Click Detected

# Switch 10
  - platform: gpio
#    name: Switch Panel 10
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    id: switch10
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW10 Single-Click Detected
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW10 Double-Click Detected

# Switch 11
  - platform: gpio
#    name: Switch Panel 11
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    id: switch11
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW11 Single-Click Detected
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW11 Double-Click Detected

# Switch 12
  - platform: gpio
#    name: Switch Panel 12
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    id: switch12
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW12 Single-Click Detected
          - if:
              condition:
                api.connected:
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.all_lights
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW12 Double-Click Detected
