substitutions:
  api_key: !secret desk-light_api_key
  board: esp32-c3-devkitm-1
  devicename: desk-light
  icon: mdi:lightbulb
  room: Desk
  device: Light
  restore: RESTORE_DEFAULT_ON
  espnow_peer_mac: 94:B5:55:26:BD:2C
  log_level: DEBUG
  color_interlock: false

<<: !include /config/configs/bulb_athom_espnow.yaml
