substitutions:
  api_key: !secret espcam01_api_key
  board: esp32-s3-devkitc-1
  devicename: espcam01
  icon: mdi:camera
  room: ""
  device: ESPCam01
  log_level: DEBUG

<<: !include /config/configs/espcam.yaml
