substitutions:
  devicename: front-porch-plug
  ntp_server: 10.0.2.1
  icon: mdi:outlet
  room: Front Porch
  device: Plug
  update_time: 10s
  # Higher value gives lower watt readout
  current_res: "0.0009"
  # Lower value gives lower voltage readout
  voltage_div: "779"

esphome:
  name: ${devicename}
  platform: ESP32
  board: esp-wrover-kit

time:
  - platform: sntp
    id: sntp_time
    servers: ${ntp_server}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  domain: !secret domain
  fast_connect: true

  ap:
    ssid: ${devicename}
    password: !secret wifi_pass
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

logger:
  level: DEBUG

mqtt:
  broker: !secret mqtt_host
  topic_prefix: esphome
  log_topic: esphome/debug/${devicename}
  birth_message:
    topic: esphome/status/${devicename}
    payload: online
  will_message:
    topic: esphome/status/${devicename}
    payload: offline
  username: !secret mqtt_username
  password: !secret mqtt_password

ota:
    password: !secret esphome_password

web_server:
  port: 80

status_led:
  pin:
    number: GPIO5
    inverted: true

output:
  - platform: gpio
    pin: GPIO19
    inverted: true
    id: relay1_led_gpio
  - platform: gpio
    pin: GPIO16
    inverted: true
    id: relay2_led_gpio

light:
  - platform: binary
    id: relay1_led
    internal: true
    output: relay1_led_gpio
  - platform: binary
    id: relay2_led
    internal: true
    output: relay2_led_gpio

switch:
  - platform: restart
    name: ${room} ${device} Restart
  - platform: gpio
    name: ${room} ${device} Relay 1
    pin:
      number: GPIO15
      inverted: false
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    name: ${room} ${device} Relay 2
    pin:
      number: GPIO32
      inverted: false
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
#  - platform: adc
#    pin: GPIO34
#    name: ${room} ${device} Illuminance
#    update_interval: ${update_time}
#    attenuation: 11db
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 5
    update_interval: ${update_time}
    current:
      name: ${room} ${device} Current
      unit_of_measurement: A
      accuracy_decimals: 1
    voltage:
      name: ${room} ${device} Voltage
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: ${room} ${device} Power
      unit_of_measurement: W
      accuracy_decimals: 1
      id: power
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58
  - platform: total_daily_energy
    name: ${room} ${device} Energy
    power_id: power
    filters:
      multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: true
    name: ${room} ${device} Button 1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: true
    name: ${room} ${device} Button 2
    on_press:
      - switch.toggle: relay2
