substitutions:
  api_key: !secret front-porch-plug_api_key
  board: esp-wrover-kit
  # Higher value gives lower watt readout
  current_res: "0.0009"
  device: Plug
  devicename: front-porch-plug
  icon: mdi:outlet
  log_level: DEBUG
  relay1_restore: RESTORE_DEFAULT_ON
  relay2_restore: ALWAYS_OFF
  room: Front Porch
  update_interval: 1s
  # Lower value gives lower voltage readout
  voltage_div: "779"

packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  esp32: !include /config/common/esp32.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

api:
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

status_led:
  pin:
    number: 5
    inverted: true
    ignore_strapping_warning: true

output:
  - platform: gpio
    pin:
      number: 19
    inverted: true
    id: relay1_led_gpio
  - platform: gpio
    pin:
      number: 16
    inverted: true
    id: relay2_led_gpio

light:
  - platform: binary
    id: relay1_led
    internal: true
    output: relay1_led_gpio
  - platform: binary
    id: relay2_led
    internal: true
    output: relay2_led_gpio

switch:
  - platform: gpio
    name: Relay 1
    pin:
      number: 15
      inverted: false
      ignore_strapping_warning: true
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
    restore_mode: ${relay1_restore}
  - platform: gpio
    name: Relay 2
    pin:
      number: 32
      inverted: false
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led
    restore_mode: ${relay2_restore}

sensor:
#  - platform: adc
#    pin:
#      number: 34
#    name: Illuminance
#    update_interval: ${update_interval}
#    attenuation: 11db
  - platform: hlw8012
    sel_pin:
      number: 25
      inverted: true
    cf_pin:
      number: 27
    cf1_pin:
      number: 26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 5
    update_interval: ${update_interval}
    current:
      name: Current
      unit_of_measurement: A
      accuracy_decimals: 1
    voltage:
      name: Voltage
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: Power
      unit_of_measurement: W
      accuracy_decimals: 1
      id: power
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58
  - platform: total_daily_energy
    name: Energy
    power_id: power
    filters:
      multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: 18
      mode: INPUT_PULLDOWN
      inverted: true
    name: Button 1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    internal: true
    pin:
      number: 17
      mode: INPUT_PULLDOWN
      inverted: true
    name: Button 2
    on_press:
      - switch.toggle: relay2
