substitutions:
  api_key: !secret front-porch-light-1_api_key
  devicename: front-porch-light-1
  icon: mdi:lightbulb
  room: Front Porch
  device: Light 1
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: front_porch_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
