substitutions:
  api_key: !secret front-porch-switch_api_key
  devicename: front-porch-switch
  icon: mdi:lightbulb
  room: Front Porch
  device: Switch
  automation_name: front_porch_switch_automation
  light_group: front_porch_lights
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_ha.yaml
