substitutions:
  api_key: !secret general-use_api_key
  devicename: general-use
  icon: mdi:power-socket-us
  room: General
  device: Use
  automation_name: general_use
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
