substitutions:
  api_key: !secret general-use_api_key
  board: esp01_1m
  devicename: general-use
  icon: mdi:power-socket-us
  room: General
  device: Use
  automation_name: general_use_automation
  restore: ALWAYS_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
