substitutions:
  api_key: !secret hobby-room-light-2_api_key
  devicename: hobby-room-light-2
  icon: mdi:lightbulb
  room: Hobby Room
  device: Light 2
  restore: RESTORE_DEFAULT_ON
  light_group: hobby_room_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
