substitutions:
  api_key: !secret hobby-room-printer_api_key
  devicename: hobby-room-printer
  icon: mdi:printer-3d
  room: Hobby Room
  device: Printer
  automation_name: hobby_room_printer_automation
  restore: ALWAYS_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
