substitutions:
  api_key: !secret hobby-room-server-1_api_key
  devicename: hobby-room-server-1
  icon: mdi:server
  room: Hobby Room
  device: Server 1
  automation_name: hobby_room_server_automation
  update_interval: 1s
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
