substitutions:
  api_key: !secret hobby-room-switch-1_api_key
  automation_name: hobby_room_light_automation
  board: esp32-c3-devkitm-1
  device: Switch 1
  devicename: hobby-room-switch-1
  espnow_peer_mac: B8:D6:1A:85:A5:58
  framework: esp-idf
  icon: mdi:light-switch
  log_level: DEBUG
  restore: ALWAYS_ON
  room: Hobby Room

<<: !include configs/switch_athom_esp32_espnow.yaml
