substitutions:
  api_key: !secret hobby-room-light-3_api_key
  devicename: hobby-room-light-3
  icon: mdi:lightbulb
  room: Hobby Room
  device: Light 3
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: hobby_room_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
