substitutions:
  api_key: !secret hobby-room-shelly_api_key
  devicename: hobby-room-shelly
  max_power: "3600.0"
  max_temp: "90.0"
  thres_temp: "75.0"
  icon1: mdi:lightbulb
  icon2: mdi:fan
  room: Hobby Room
  device: Shelly
  channel_1: Light
  channel_2: Fan
  update_time: 10s
  light_group: hobby_room_lights
  log_level: DEBUG

<<: !include /config/configs/hobby_room_shelly_2pm_ha.yaml
