substitutions:
  api_key: !secret hobby-room-shelly_api_key
  devicename: hobby-room-shelly
  max_power: "3600.0"
  max_temp: "90.0"
  thres_temp: "75.0"
  icon1: mdi:lightbulb
  icon2: mdi:fan
  room: Hobby Room
  device: Shelly
  automation_name: hobby_room_light_automation
  relay1: Light
  relay2: Fan
  update_interval: 1s
  log_level: DEBUG

<<: !include /config/configs/shelly_2pm.yaml
