substitutions:
  api_key: !secret inside-sniffer_api_key
  board: featheresp32
  device: Sniffer
  devicename: inside-sniffer
  framework: esp-idf
  log_level: DEBUG
  room: Inside
  send_every: '10'
  temp_offset: '8.7'
  update_interval: 1s

<<: !include configs/sniffer.yaml
