substitutions:
  api_key: !secret kitchen-light-5_api_key
  devicename: kitchen-light-5
  icon: mdi:lightbulb
  room: Kitchen
  device: Light 5
  restore: RESTORE_DEFAULT_ON
  light_group: kitchen_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
