substitutions:
  api_key: !secret kitchen-switch-1_api_key
  board: esp01_1m
  devicename: kitchen-switch-1
  icon: mdi:lightbulb
  room: Kitchen
  device: Switch 1
  automation_name: kitchen_light_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_gosund.yaml
