substitutions:
  api_key: !secret kitchen-coffee_api_key
  devicename: kitchen-coffee
  icon: mdi:coffee
  room: Kitchen
  device: Coffee
  automation_name: coffee_automation
  update_time: 10s
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha_automation.yaml
