substitutions:
  api_key: !secret kitchen-light-3_api_key
  devicename: kitchen-light-3
  icon: mdi:lightbulb
  room: Kitchen
  device: Light 3
  restore: RESTORE_DEFAULT_ON
  light_group: kitchen_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
