substitutions:
  api_key: !secret kitchen-switch-2_api_key
  devicename: kitchen-switch-2
  icon: mdi:lightbulb
  room: Kitchen
  device: Switch 2
  automation_name: kitchen_light_automation
  log_level: DEBUG

<<: !include configs/switch_gosund.yaml
