substitutions:
  api_key: !secret kitchen-fridge_api_key
  automation_name: kitchen_fridge_automation
  board: esp01_1m
  device: Fridge
  devicename: kitchen-fridge
  icon: mdi:fridge-variant
  log_level: DEBUG
  restore: ALWAYS_ON
  room: Kitchen

<<: !include /config/configs/sonoff_s31.yaml
