substitutions:
  devicename: kitchen-switch-1
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_pass
  domain: !secret domain
  use_address: 10.0.41.32
  password: !secret esphome_password
  ntp_server: 10.0.2.1
  icon: mdi:lightbulb
  room: Kitchen
  device: Switch 1

esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

time:
  - platform: sntp
    id: sntp_time
    servers: ${ntp_server}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  domain: ${domain}
  use_address: ${use_address}

  ap:
    ssid: ${devicename}
    password: ${password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

logger:
  level: DEBUG

api:
  password: ${password}

ota:
  password: ${password}

web_server:
  port: 80

switch:
  - platform: restart
    name: ${room} ${device} Restart
#  - platform: gpio
#    pin: GPIO14
#    id: relay1
#    name: ${room} ${device}
#    icon: ${icon}
#    restore_mode: RESTORE_DEFAULT_OFF
#    on_turn_on:
#      - light.turn_on: led
#    on_turn_off:
#      - light.turn_off: led

status_led:
  pin:
    number: GPIO16
    inverted: true

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO2
      inverted: true

light:
  - platform: monochromatic
    output: state_led
    id: led

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      inverted: true
    id: button1
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: Single-Click Detected
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.kitchen_lights
                effect: 'none'
                kelvin: '3000'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: Double-Click Detected
          - homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.kitchen_lights
                effect: "Color Cycle"
                kelvin: '3000'