substitutions:
  api_key: !secret kitchen-fridge_api_key
  devicename: kitchen-fridge
  icon: mdi:fridge-variant
  room: Kitchen
  device: Fridge
  automation_name: kitchen_fridge_automation
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
