substitutions:
  api_key: !secret kitchen-switch-1_api_key
  devicename: kitchen-switch-1
  icon: mdi:lightbulb
  room: Kitchen
  device: Switch 1
  automation_name: kitchen_lights
  update_time: 10s
  light_group: kitchen_lights
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include configs/switch_ha.yaml
