substitutions:
  api_key: !secret kitchen-light-4_api_key
  devicename: kitchen-light-4
  icon: mdi:lightbulb
  room: Kitchen
  device: Light 4
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: kitchen_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
