substitutions:
  api_key: !secret kitchen-switch-1_api_key
  automation_name: kitchen_light_automation
  board: esp01_1m
  device: Switch 1
  devicename: kitchen-switch-1
  icon: mdi:light-switch
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Kitchen

<<: !include configs/switch_gosund.yaml
