substitutions:
  api_key: !secret kitchen-switch-2_api_key
  devicename: kitchen-switch-2
  icon: mdi:lightbulb
  room: Kitchen
  device: Switch 2
  automation_name: kitchen_lights_automation
  light_group: kitchen_lights
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include configs/switch_ha.yaml
