substitutions:
  api_key: !secret kitchen-coffee_api_key
  board: esp01_1m
  devicename: kitchen-coffee
  icon: mdi:coffee
  room: Kitchen
  device: Coffee
  automation_name: coffee_automation
  restore: ALWAYS_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
