substitutions:
  api_key: !secret kitchen-lamp_api_key
  devicename: kitchen-lamp
  icon: mdi:lamp
  room: Kitchen
  device: Lamp
  automation_name: kitchen_lamp_automation
  update_interval: 1s
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
