substitutions:
  api_key: !secret kitchen-lamp_api_key
  devicename: kitchen-lamp
  icon: mdi:lamp
  room: Kitchen
  device: Lamp
  automation_name: kitchen_lamp
  update_time: 10s
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG
  #log_level: VERY_VERBOSE

<<: !include /config/configs/sonoff_s31_ha.yaml
