substitutions:
  api_key: !secret living-room-desktop_api_key
  devicename: living-room-desktop
  icon: mdi:desktop-classic
  room: Living Room
  device: Desktop
  automation_name: living_room_desktop_automation
  restore: ALWAYS_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
