substitutions:
  api_key: !secret living-room-desk_api_key
  board: esp01_1m
  devicename: living-room-desk
  icon: mdi:desktop-classic
  room: Living Room
  device: Desk
  automation_name: living_room_desk_automation
  restore: ALWAYS_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
