substitutions:
  api_key: !secret living-room-desktop_api_key
  devicename: living-room-desktop
  icon: mdi:desktop-classic
  room: Living Room
  device: Desktop
  automation_name: living_room_desktop
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31_ha.yaml
