substitutions:
  api_key: !secret living-room-ble-tracker_api_key
  board: wemos_d1_mini32
  devicename: living-room-ble-tracker
  room: Living Room
  device: BLE Tracker
  update_interval: 15s
  log_level: DEBUG

packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  esp32: !include /config/common/esp32.yaml
  esphome: !include /config/common/esphome.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

status_led:
    pin:
      number: 2
      inverted: true
      ignore_strapping_warning: true
