substitutions:
  api_key: !secret living-room-shelly_api_key
  automation_name: living_room_light_automation
  board: esp32doit-devkit-v1
  device: Shelly
  devicename: living-room-shelly
  framework: esp-idf
  icon1: mdi:lightbulb
  icon2: mdi:fan
  log_level: DEBUG
  max_power: "3600.0"
  max_temp: "90.0"
  relay1_restore: RESTORE_DEFAULT_OFF
  relay1: Light
  relay2_restore: ALWAYS_ON
  relay2: Fan
  room: Living Room
  thres_temp: "75.0"
  update_interval: 1s

<<: !include /config/configs/shelly_2pm.yaml
