substitutions:
  api_key: !secret living-room-shelly_api_key
  devicename: living-room-shelly
  max_power: "3600.0"
  max_temp: "90.0"
  thres_temp: "75.0"
  icon1: mdi:lightbulb
  icon2: mdi:fan
  room: Living Room
  device: Shelly
  automation_name: living_room_light_automation
  relay1: Light
  relay2: Fan
  relay1_restore: RESTORE_DEFAULT_OFF
  relay2_restore: ALWAYS_ON
  update_interval: 1s
  log_level: DEBUG

<<: !include /config/configs/shelly_2pm.yaml
