substitutions:
  api_key: !secret living-room-light-2_api_key
  devicename: living-room-light-2
  icon: mdi:lightbulb
  room: Living Room
  device: Light 2
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: living_room_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
