substitutions:
  devicename: outside-power-meter
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_pass
  domain: !secret domain
  use_address: 10.0.41.36
  password: !secret esphome_password
  ntp_server: 10.0.2.1
  icon: mdi:gauge
  room: Outside
  device: Power Meter
  #automation:
  # Interval of how often the power is updated
  update_time: 10s
  # Current transformer calibrations:
  # 80A/26.6mA SCT-010: 39571
  # 100A/50mA SCT-013: 26315
  # 120A/40ma SCT-016: 39473 - default kit CT
  # 200A/100mA SCT-024: 26315
  current_cal: "39473"
  # AC Transformer voltage calibration 9VAC Jameco 157041: 37106
  # For Meters >= v1.4 rev3: 3920
  voltage_cal: "3920"

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

time:
  - platform: sntp
    id: sntp_time
    servers: ${ntp_server}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  domain: ${domain}
  use_address: ${use_address}

  ap:
    ssid: ${devicename}
    password: ${password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

logger:
  level: DEBUG

api:
  password: ${password}

ota:
  password: ${password}

web_server:
  port: 80

switch:
  - platform: restart
    name: ${room} ${device} Restart

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

sensor:
  - platform: wifi_signal
    name: ${room} ${device} WiFi Signal
    update_interval: 60s
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${room} ${device} Voltage
        accuracy_decimals: 1
      current:
        name: ${room} ${device} CT1 Current
        accuracy_decimals: 1
        id: "ct1Amps"
      # The max value for current that the meter can output is 65.535. If you expect to measure current over 65A,
      # divide the gain_ct by 2 (120A CT) or 4 (200A CT) and multiply the current and power values by 2 or 4 by uncommenting the filter below
      #        filters:
      #          - multiply: 2
      power:
        name: ${room} ${device} CT1 Power
        accuracy_decimals: 1
        id: "ct1Watts"
      #        filters:
      #          - multiply: 2
      reactive_power:
        name: ${room} ${device} CT1 Reactive Power
        accuracy_decimals: 1
        id: "ct1Reactive"
      #        filters:
      #          - multiply: 2
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    phase_c:
      current:
        name: ${room} ${device} CT2 Current
        accuracy_decimals: 1
        id: "ct2Amps"
      # The max value for current that the meter can output is 65.535. If you expect to measure current over 65A,
      # divide the gain_ct by 2 (120A CT) or 4 (200A CT) and multiply the current and power values by 2 or 4 by uncommenting the filter below
      #        filters:
      #          - multiply: 2
      power:
        name: ${room} ${device} CT2 Power
        accuracy_decimals: 1
        id: "ct2Watts"
      #        filters:
      #          - multiply: 2
      reactive_power:
        name: ${room} ${device} CT2 Reactive Power
        accuracy_decimals: 1
        id: "ct2Reactive"
      #        filters:
      #          - multiply: 2
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}
    frequency:
      name: ${room} ${device} Freq
    chip_temperature:
      name: ${room} ${device} Chip Temp
    line_frequency: 60Hz
    gain_pga: 2X
    update_interval: ${update_time}
  - platform: template
    name: ${room} ${device} Total Current
    id: "totalAmps"
    lambda: return id(ct1Amps).state + id(ct2Amps).state;
    accuracy_decimals: 1
    unit_of_measurement: A
    update_interval: ${update_time}
    icon: "mdi:current-ac"
  - platform: template
    name: ${room} ${device} Total Power
    id: "totalWatts"
    lambda: return id(ct1Watts).state + id(ct2Watts).state;
    accuracy_decimals: 1
    unit_of_measurement: W
    icon: "mdi:power"
    update_interval: ${update_time}
  - platform: template
    name: ${room} ${device} Total Reactive Power
    id: "totalReactivePower"
    lambda: return id(ct1Reactive).state + id(ct2Reactive).state;
    accuracy_decimals: 1
    unit_of_measurement: VAR
    icon: "mdi:flash-circle"
    update_interval: ${update_time}

  - platform: total_daily_energy
    name: ${room} ${device} Total Energy
    power_id: totalWatts
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh