substitutions:
  api_key: !secret outside-sniffer_api_key
  board: featheresp32
  device: Sniffer
  devicename: outside-sniffer
  framework: esp-idf
  log_level: DEBUG
  room: Outside
  send_every: '10'
  temp_offset: '6.0'
  update_interval: 1s

<<: !include configs/sniffer.yaml
