substitutions:
  api_key: !secret switch-panel_api_key
  devicename: switch-panel
  ntp_server: 10.69.2.1
  room: Switch
  device: Panel
  update_time: 10s
#  log_level: VERY_VERBOSE
  log_level: DEBUG

esphome:
  name: ${devicename}

esp32:
  board: wemos_d1_mini32

packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor_ble.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  #mqtt: !include /config/common/mqtt.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
#  sensor: !include /config/common/sensor_ble.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

status_led:
    pin:
      number: 2
      inverted: false

binary_sensor:
## Switch Panel
# Switch 1
  - platform: gpio
#    name: Switch Panel 1
    pin:
      number: GPIO32
      mode: INPUT_PULLUP
      inverted: true
    id: switch1
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW1 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: bath_1_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.bath_1_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.bath_1_lights
#                - mqtt.publish:
#                    topic: remote/bath_1_lights/command
#                    payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.bath_1_lights
#                - mqtt.publish:
#                    topic: remote/bath_1_lights/command
#                    payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW1 Double-Click Detected

# Switch 2
  - platform: gpio
#    name: Switch Panel 2
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    id: switch2
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW2 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: bedroom_1_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.bedroom_1_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.bedroom_1_lights
#                - mqtt.publish:
#                    topic: remote/bedroom_1_lights/command
#                    payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.bedroom_1_lights
#                - mqtt.publish:
#                    topic: remote/bedroom_1_lights/command
#                    payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW2 Double-Click Detected
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.bedroom_1_lamp
#          - mqtt.publish:
#              topic: esphome/switch/bedroom_1_lamp/command
#              payload: 'toggle'

# Switch 3
  - platform: gpio
#    name: Switch Panel 3
    pin:
      number: GPIO05
      mode: INPUT_PULLUP
      inverted: true
    id: switch3
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW3 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: bath_2_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.bath_2_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.bath_2_lights
#                - mqtt.publish:
#                    topic: remote/bath_2_lights/command
#                    payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.bath_2_lights
#                - mqtt.publish:
#                    topic: remote/bath_2_lights/command
#                    payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW3 Double-Click Detected

# Switch 4
  - platform: gpio
#    name: Switch Panel 4
    pin:
      number: GPIO23
      mode: INPUT_PULLUP
      inverted: true
    id: switch4
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW4 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: bedroom_2_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.bedroom_2_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.bedroom_2_lights
#                - mqtt.publish:
#                    topic: remote/bedroom_2_lights/command
#                    payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.bedroom_2_lights
#                - mqtt.publish:
#                    topic: remote/bedroom_2_lights/command
#                    payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW4 Double-Click Detected

# Switch 5
  - platform: gpio
#    name: Switch Panel 5
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    id: switch5
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW5 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: hobby_room_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.hobby_room_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.hobby_room_lights
#                - mqtt.publish:
#                    topic: remote/hobby_room_lights/command
#                    payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.hobby_room_lights
#                - mqtt.publish:
#                    topic: remote/hobby_room_lights/command
#                    payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW5 Double-Click Detected

# Switch 6
  - platform: gpio
#    name: Switch Panel 6
    pin:
      number: GPIO17
      mode: INPUT_PULLUP
      inverted: true
    id: switch6
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW6 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: kitchen_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.kitchen_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.kitchen_lights
#                - mqtt.publish:
#                   topic: remote/kitchen_lights/command
#                   payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.kitchen_lights
#                - mqtt.publish:
#                   topic: remote/kitchen_lights/command
#                   payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW6 Double-Click Detected
          - homeassistant.service:
              service: switch.toggle
              data:
                entity_id: switch.kitchen_lamp
#          - mqtt.publish:
#              topic: esphome/switch/kitchen_lamp/command
#              payload: 'toggle'

# Switch 7
  - platform: gpio
#    name: Switch Panel 7
    pin:
      number: GPIO25
      mode: INPUT_PULLUP
      inverted: true
    id: switch7
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW7 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: living_room_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.living_room_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.living_room_lights
#                - mqtt.publish:
#                   topic: remote/living_room_lights/command
#                   payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.living_room_lights
#                - mqtt.publish:
#                   topic: remote/living_room_lights/command
#                   payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW7 Double-Click Detected

# Switch 8
  - platform: gpio
#    name: Switch Panel 8
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true
    id: switch8
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW8 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: utility_room_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.utility_room_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.utility_room_lights
#                - mqtt.publish:
#                   topic: remote/utility_room_lights/command
#                   payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.utility_room_lights
#                - mqtt.publish:
#                   topic: remote/utility_room_lights/command
#                   payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW8 Double-Click Detected

# Switch 9
  - platform: gpio
#    name: Switch Panel 9
    pin:
      number: GPIO26
      mode: INPUT_PULLUP
      inverted: true
    id: switch9
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW9 Single-Click Detected
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.front_porch_lights
#          - mqtt.publish:
#              topic: esphome/switch/front_porch_light/command
#              payload: 'toggle'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW9 Double-Click Detected

# Switch 10
  - platform: gpio
#    name: Switch Panel 10
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true
    id: switch10
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW10 Single-Click Detected
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW10 Double-Click Detected

# Switch 11
  - platform: gpio
#    name: Switch Panel 11
    pin:
      number: GPIO22
      mode: INPUT_PULLUP
      inverted: true
    id: switch11
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW11 Single-Click Detected
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW11 Double-Click Detected

# Switch 12
  - platform: gpio
#    name: Switch Panel 12
    pin:
      number: GPIO33
      mode: INPUT_PULLUP
      inverted: true
    id: switch12
    on_multi_click:
      - timing:
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW12 Single-Click Detected
          - if:
              condition:
                api.connected:
#                text_sensor.state:
#                  id: all_lights_state
#                  state: 'off'
              then:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.all_lights
#                - homeassistant.service:
#                    service: light.turn_on
#                    data:
#                      entity_id: light.all_lights
#                - mqtt.publish:
#                   topic: remote/all_lights/command
#                   payload: 'on'
#              else:
#                - homeassistant.service:
#                    service: light.turn_off
#                    data:
#                      entity_id: light.all_lights
#                - mqtt.publish:
#                   topic: remote/all_lights/command
#                   payload: 'off'
      - timing:
          - ON for at most 400ms
          - OFF for at most 250ms
          - ON for at most 400ms
          - OFF for at least 250ms
        then:
          - logger.log: SW12 Double-Click Detected

#text_sensor:
#  - platform: homeassistant
#    id: all_lights_state
#    entity_id: light.all_lights
#    name: Switch Panel All Lights State
#
#  - platform: homeassistant
#    id: bath_1_lights_state
#    entity_id: light.bath_1_lights
#    name: Switch Panel Bath 1 Light State
#
#  - platform: homeassistant
#    id: bath_2_lights_state
#    entity_id: light.bath_2_lights
#    name: Switch Panel Bath 2 Light State
#
#  - platform: homeassistant
#    entity_id: light.bedroom_1_lights
#    id: bedroom_1_lights_state
#    name: Switch Panel Bedroom 1 Light State
#
#  - platform: homeassistant
#    entity_id: light.bedroom_2_lights
#    id: bedroom_2_lights_state
#    name: Switch Panel Bedroom 2 Light State
#
#  - platform: homeassistant
#    entity_id: light.hobby_room_lights
#    id: hobby_room_lights_state
#    name: Switch Panel Hobby Room Light State
#
#  - platform: homeassistant
#    entity_id: light.kitchen_lights
#    id: kitchen_lights_state
#    name: Switch Panel Kitchen Light State
#
#  - platform: homeassistant
#    entity_id: light.living_room_lights
#    id: living_room_lights_state
#    name: Switch Panel Living Room Light State
#
#  - platform: homeassistant
#    entity_id: light.utility_room_lights
#    id: utility_room_lights_state
#    name: Switch Panel Utility Room Light State
#
#  - platform: mqtt_subscribe
#    id: all_lights_state
#    #name: Switch Panel All Lights State
#    topic: ha-core/light/all_lights/state
#
#  - platform: mqtt_subscribe
#    id: bath_1_lights_state
#    #name: Switch Panel Bath 1 Light State
#    topic: ha-core/light/bath_1_lights/state
#
#  - platform: mqtt_subscribe
#    id: bath_2_lights_state
#    #name: Switch Panel Bath 2 Light State
#    topic: ha-core/light/bath_2_lights/state
#
#  - platform: mqtt_subscribe
#    id: bedroom_1_lights_state
#    #name: Switch Panel Bedroom 1 Light State
#    topic: ha-core/light/bedroom_1_lights/state
#
#  - platform: mqtt_subscribe
#    id: bedroom_2_lights_state
#    #name: Switch Panel Bedroom 2 Light State
#    topic: ha-core/light/bedroom_2_lights/state
#
#  - platform: mqtt_subscribe
#    id: hobby_room_lights_state
#    #name: Switch Panel Hobby Room Light State
#    topic: ha-core/light/hobby_room_lights/state
#
#  - platform: mqtt_subscribe
#    id: kitchen_lights_state
#    #name: Switch Panel Kitchen Light State
#    topic: ha-core/light/kitchen_lights/state
#
#  - platform: mqtt_subscribe
#    id: living_room_lights_state
#    #name: Switch Panel Living Room Light State
#    topic: ha-core/light/living_room_lights/state
#
#  - platform: mqtt_subscribe
#    id: utility_room_lights_state
#    #name: Switch Panel Utility Room Light State
#    topic: ha-core/light/utility_room_lights/state
