substitutions:
  api_key: !secret test-light-1_api_key
  devicename: test-light-1
  icon: mdi:lightbulb
  room: Test
  device: Light 1
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: test_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
