
substitutions:
  devicename: test
  wifi_ssid: !secret wifi_ssid
  wifi_pass: !secret wifi_pass
  domain: !secret domain
  use_address: 10.0.41.254
  password: !secret esphome_password
  ntp_server: 10.0.2.1
  device: Test
  #automation:

esphome:
  name: ${devicename}
  platform: ESP32
  board: nodemcu-32s

time:
  - platform: sntp
    id: sntp_time
    servers: ${ntp_server}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_pass}
  domain: ${domain}
  use_address: ${use_address}

  ap:
    ssid: ${devicename}
    password: ${password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0

captive_portal:

logger:
  level: DEBUG

api:
  password: ${password}

ota:
  password: ${password}

web_server:
  port: 80

status_led:
  pin: GPIO2

switch:
  - platform: restart
    name: ${device} Restart

sensor:
  - platform: wifi_signal
    name: ${device} RSSI
    update_interval: 1s
