substitutions:
  api_key: !secret utility-room-switch-2_api_key
  automation_name: back_porch_light_automation
  board: esp32-c3-devkitm-1
  device: Switch 1
  devicename: utility-room-switch-2
  icon: mdi:light-switch
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Utility Room

<<: !include configs/switch_athom_esp32.yaml
