substitutions:
  api_key: !secret utility-room-switch-2_api_key
  board: esp32-c3-devkitm-1
  devicename: utility-room-switch-2
  icon: mdi:light-switch
  room: Hobby Room
  device: Switch 1
  automation_name: back_porch_light_automation
  restore: RESTORE_DEFAULT_OFF
  log_level: DEBUG

<<: !include configs/switch_athom_esp32.yaml
