substitutions:
  api_key: !secret utility-room-light-1_api_key
  devicename: utility-room-light-1
  icon: mdi:lightbulb
  room: Utility Room
  device: Light 1
  update_time: 10s
  restore: RESTORE_DEFAULT_ON
  light_group: utility_room_lights
  log_level: DEBUG

<<: !include /config/configs/kauf_blf10_ha.yaml
