substitutions:
  api_key: !secret utility-room-washer_api_key
  devicename: utility-room-washer
  icon: mdi:washing-machine
  room: Utility Room
  device: Washer
  automation_name: utility_room_washer_automation
  update_interval: 1s
  restore: ALWAYS_ON
  log_level: DEBUG

<<: !include /config/configs/sonoff_s31.yaml
