substitutions:
  api_key: !secret utility-room-switch-1_api_key
  automation_name: utility_room_light_automation
  board: esp01_1m
  device: Switch 1
  devicename: utility-room-switch-1
  icon: mdi:light-switch
  log_level: DEBUG
  restore: RESTORE_DEFAULT_OFF
  room: Utility Room

<<: !include configs/switch_gosund.yaml
