substitutions:
  api_key: !secret utility-room-switch-1_api_key
  devicename: utility-room-switch-1
  icon: mdi:lightbulb
  room: Utility Room
  device: Switch 1
  automation_name: utility_room_light_automation
  log_level: DEBUG

<<: !include configs/switch_gosund.yaml
