wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  #domain: !secret domain
  fast_connect: true
  reboot_timeout: 0s
#  power_save_mode: none
  output_power: 17
  min_auth_mode: WPA2

sensor:
  - platform: wifi_signal
    name: WiFi RSSI
    id: wifi_signal_rssi
    update_interval: 10s
  - platform: copy
    source_id: wifi_signal_rssi
    name: WiFi Signal
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"
    entity_category: "diagnostic"
    device_class: ""

text_sensor:
  - platform: wifi_info
    ip_address:
      id: ip_address
      address_0:
        name: IP Address 0
      address_1:
        name: IP Address 1
      address_2:
        name: IP Address 2
    ssid:
      name: SSID
      id: ssid
    mac_address:
      name: MAC Address
      id: mac_address
    bssid:
      name: BSSID
