esphome:
  name: ${devicename}

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino


  #board: esp32doit-devkit-v1
#  restore_from_flash: true

packages:
  api: !include /config/common/api.yaml
  binary_sensor: !include /config/common/binary_sensor_ble.yaml
  esp32_ble_tracker: !include /config/common/esp32_ble_tracker.yaml
  captive_portal: !include /config/common/captive_portal.yaml
  logger: !include /config/common/logger.yaml
  ota: !include /config/common/ota.yaml
  sensor: !include /config/common/sensor.yaml
#  sensor: !include /config/common/sensor_ble.yaml
  switch: !include /config/common/switch.yaml
  text_sensor: !include /config/common/text_sensor.yaml
  time: !include /config/common/time.yaml
  web_server: !include /config/common/web_server.yaml
  wifi: !include /config/common/wifi.yaml

switch:
  - platform: gpio
    name: ${room} ${channel_1}
    pin: GPIO13
    id: light
    icon: ${icon1}
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: ${room} ${channel_2}
    pin: GPIO12
    id: fan
    icon: ${icon2}
    restore_mode: ALWAYS_ON

i2c:
  sda: GPIO26
  scl: GPIO25

sensor:
  - platform: ade7953_i2c
    irq_pin: GPIO27
    update_interval: ${update_time}
    voltage:
      name: ${room} ${device} Voltage
    current_a:
      name: ${room} ${channel_2} Current
    current_b:
      name: ${room} ${channel_1} Current
    active_power_a:
      name: ${room} ${channel_2} Power
      id: power_channel_2
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: light
#            - homeassistant.service:
#                service: persistent_notification.create
#                data:
#                  title: Message from ${devicename}
#                data_template:
#                  message: Switch turned off because power exceeded ${max_power}W
    active_power_b:
      name: ${room} ${channel_1} Power
      id: power_channel_1
      filters:
        - multiply: -1
        - lambda: |-
            if (x >= 0) return x;
            else x=0; return x;
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: fan
#            - homeassistant.service:
#                service: persistent_notification.create
#                data:
#                  title: Message from ${devicename}
#                data_template:
#                  message: Switch turned off because power exceeded ${max_power}W
  - platform: total_daily_energy
    name: ${room} ${channel_1} Energy
    power_id: power_channel_1
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${room} ${channel_2} Energy
    power_id: power_channel_2
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${room} ${device} Temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
#          - switch.turn_off: light
          - switch.turn_off: fan
#          - homeassistant.service:
#              service: persistent_notification.create
#              data:
#                title: Message from ${devicename}
#              data_template:
#                message: Switch turned off because temperature exceeded ${max_temp}°C
#      - below: ${thres_temp}
#        then:
#          - switch.turn_on: fan
#          - homeassistant.service:
#              service: persistent_notification.create
#              data:
#                title: Message from ${devicename}
#              data_template:
#                message: Fan turned on because temperature is below ${thres_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO35
    update_interval: ${update_time}

status_led:
  pin:
    number: GPIO0
    inverted: yes

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    id: ${channel_1}_input
    on_state:
      then:
        - logger.log: Single-Click Detected
        - if:
            condition:
              api.connected:
            then:
              - homeassistant.service:
                  service: light.toggle
                  data:
                    entity_id: light.${light_group}
  - platform: gpio
    pin:
      number: GPIO18
    id: ${channel_2}_input
    filters:
      - delayed_off: 3s
